<?php

namespace ContainerZxMCIEv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NVC8X7EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nVC8X7E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nVC8X7E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'battleground' => ['privates', 'App\\Service\\Battleground', 'getBattlegroundService', true],
        ], [
            'battleground' => 'App\\Service\\Battleground',
        ]);
    }
}
