<?php

namespace ContainerZxMCIEv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBattlegroundService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Battleground' shared autowired service.
     *
     * @return \App\Service\Battleground
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Battleground.php';

        return $container->privates['App\\Service\\Battleground'] = new \App\Service\Battleground();
    }
}
